version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: Eduscript
      POSTGRES_USER: Eduscript
      POSTGRES_PASSWORD: Eduscript_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - Eduscript-network

  app:
    build: .
    environment:
      DATABASE_URL: "postgresql://Eduscript:Eduscript_password@db:5432/Eduscript"
      NEXTAUTH_SECRET: "change-this-secret-in-production"
      NEXTAUTH_URL: "http://localhost:3000"
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - Eduscript-network
    volumes:
      - ./public/uploads:/app/public/uploads

volumes:
  postgres_data:

networks:
  Eduscript-network:
    driver: bridge
