#!/usr/bin/env bash
# Eduskript Development Environment Setup
# Automatically configures PostgreSQL and Next.js with unique ports for worktree-safe development

set -e

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Configuration
POSTGRES_PORT_RANGE_START=5432
POSTGRES_PORT_RANGE_END=5532
NEXTJS_PORT_RANGE_START=3000
NEXTJS_PORT_RANGE_END=3100

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}    Eduskript Development Environment Setup${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# Check if running in git worktree
WORKTREE_PATH=$(git rev-parse --show-toplevel 2>/dev/null || echo "")
WORKTREE_NAME=$(basename "$WORKTREE_PATH")

if [ -n "$WORKTREE_PATH" ]; then
    echo -e "${GREEN}✓${NC} Detected worktree: ${YELLOW}$WORKTREE_NAME${NC}"
else
    echo -e "${YELLOW}⚠${NC} Not in a git repository. Continuing anyway..."
fi

echo ""

# Check if node_modules exists, if not run pnpm install
if [ ! -d "node_modules" ]; then
    echo -e "${BLUE}→${NC} Installing dependencies (first time setup)..."
    if pnpm install; then
        echo -e "${GREEN}✓${NC} Dependencies installed"
    else
        echo -e "${RED}✗ Error: Failed to install dependencies${NC}"
        exit 1
    fi
    echo ""
fi

# Function to check if port is available
is_port_available() {
    local port=$1
    if command -v lsof &> /dev/null; then
        ! lsof -Pi :$port -sTCP:LISTEN -t >/dev/null 2>&1
    elif command -v netstat &> /dev/null; then
        ! netstat -tuln 2>/dev/null | grep -q ":$port "
    elif command -v ss &> /dev/null; then
        ! ss -tuln 2>/dev/null | grep -q ":$port "
    else
        echo -e "${RED}✗ Error: Cannot check port availability (no lsof, netstat, or ss found)${NC}"
        exit 1
    fi
}

# Function to find available port in range
find_available_port() {
    local start=$1
    local end=$2
    local service_name=$3

    for port in $(seq $start $end); do
        if is_port_available $port; then
            echo $port
            return 0
        fi
    done

    echo -e "${RED}✗ Error: No available ports found for $service_name in range $start-$end${NC}" >&2
    return 1
}

# Check if .env.local already exists
if [ -f ".env.local" ]; then
    echo -e "${YELLOW}⚠${NC} .env.local already exists"
    read -p "  Do you want to regenerate it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo -e "${BLUE}→${NC} Using existing .env.local configuration"
        source .env.local
        POSTGRES_PORT=${POSTGRES_PORT:-5432}
        PORT=${PORT:-3000}
        echo ""
        echo -e "${GREEN}✓${NC} PostgreSQL port: ${YELLOW}$POSTGRES_PORT${NC}"
        echo -e "${GREEN}✓${NC} Next.js port: ${YELLOW}$PORT${NC}"

        # Skip to Docker setup
        SKIP_PORT_DETECTION=true
    fi
fi

# Find available ports (if not skipped)
if [ -z "$SKIP_PORT_DETECTION" ]; then
    echo -e "${BLUE}→${NC} Finding available ports..."

    POSTGRES_PORT=$(find_available_port $POSTGRES_PORT_RANGE_START $POSTGRES_PORT_RANGE_END "PostgreSQL")
    if [ $? -ne 0 ]; then
        exit 1
    fi
    echo -e "${GREEN}✓${NC} PostgreSQL port: ${YELLOW}$POSTGRES_PORT${NC}"

    NEXTJS_PORT=$(find_available_port $NEXTJS_PORT_RANGE_START $NEXTJS_PORT_RANGE_END "Next.js")
    if [ $? -ne 0 ]; then
        exit 1
    fi
    echo -e "${GREEN}✓${NC} Next.js port: ${YELLOW}$NEXTJS_PORT${NC}"

    # Generate .env.local
    echo ""
    echo -e "${BLUE}→${NC} Generating .env.local..."

    cat > .env.local <<EOF
# Auto-generated by setup-dev.sh
# This file is specific to this worktree and should not be committed

# PostgreSQL Configuration
POSTGRES_PORT=$POSTGRES_PORT
POSTGRES_CONTAINER_NAME=eduskript-postgres-$POSTGRES_PORT
POSTGRES_VOLUME_NAME=eduskript_postgres_data_$POSTGRES_PORT

# Database URL
DATABASE_URL="postgresql://postgres:password@localhost:$POSTGRES_PORT/eduskript_dev"

# Next.js Configuration
PORT=$NEXTJS_PORT
NEXTAUTH_URL=http://localhost:$NEXTJS_PORT

# NextAuth Secret (generate a new one for production!)
NEXTAUTH_SECRET=$(openssl rand -base64 32 2>/dev/null || echo "development-secret-$(date +%s)")
EOF

    echo -e "${GREEN}✓${NC} Created .env.local"
fi

# Load environment variables
export $(grep -v '^#' .env.local | xargs)

# Check if Docker is running
if ! docker info >/dev/null 2>&1; then
    echo ""
    echo -e "${RED}✗ Error: Docker is not running${NC}"
    echo -e "${YELLOW}  Please start Docker and run this script again${NC}"
    exit 1
fi

# Start PostgreSQL container
echo ""
echo -e "${BLUE}→${NC} Setting up PostgreSQL container..."

# Check if container already exists
if docker ps -a --format '{{.Names}}' | grep -q "^$POSTGRES_CONTAINER_NAME$"; then
    echo -e "${YELLOW}⚠${NC} Container $POSTGRES_CONTAINER_NAME already exists"

    # Check if it's running
    if docker ps --format '{{.Names}}' | grep -q "^$POSTGRES_CONTAINER_NAME$"; then
        echo -e "${GREEN}✓${NC} Container is already running"
    else
        echo -e "${BLUE}→${NC} Starting existing container..."
        docker start $POSTGRES_CONTAINER_NAME
        echo -e "${GREEN}✓${NC} Container started"
    fi
else
    echo -e "${BLUE}→${NC} Creating PostgreSQL container..."
    docker compose -f docker-compose.local.yml up -d
    echo -e "${GREEN}✓${NC} Container created and started"
fi

# Wait for PostgreSQL to be ready
echo -e "${BLUE}→${NC} Waiting for PostgreSQL to be ready..."
for i in {1..30}; do
    if docker exec $POSTGRES_CONTAINER_NAME pg_isready -U postgres >/dev/null 2>&1; then
        echo -e "${GREEN}✓${NC} PostgreSQL is ready"
        break
    fi
    if [ $i -eq 30 ]; then
        echo -e "${RED}✗ Error: PostgreSQL failed to start${NC}"
        exit 1
    fi
    sleep 1
done

# Generate Prisma client (needs DATABASE_URL even though we just generated .env.local)
echo ""
echo -e "${BLUE}→${NC} Generating Prisma client..."
# Export DATABASE_URL for this command since Prisma config needs it
if DATABASE_URL="$DATABASE_URL" pnpm db:generate; then
    echo -e "${GREEN}✓${NC} Prisma client generated"
else
    echo -e "${RED}✗ Error: Failed to generate Prisma client${NC}"
    exit 1
fi

# Run database migrations
echo ""
echo -e "${BLUE}→${NC} Running database migrations..."
if pnpm prisma migrate deploy; then
    echo -e "${GREEN}✓${NC} Migrations applied"
else
    echo -e "${YELLOW}⚠${NC} Migration failed - database might already be up to date"
fi

# Seed admin user
echo ""
echo -e "${BLUE}→${NC} Seeding admin user..."
if node scripts/seed-admin-sql.mjs; then
    echo -e "${GREEN}✓${NC} Admin user seeded (or already exists)"
else
    echo -e "${YELLOW}⚠${NC} Admin user seeding failed - user might already exist"
fi

# Print success message
echo ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}    ✓ Development Environment Ready!${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${BLUE}PostgreSQL:${NC}"
echo -e "  Port:      ${YELLOW}$POSTGRES_PORT${NC}"
echo -e "  Container: ${YELLOW}$POSTGRES_CONTAINER_NAME${NC}"
echo -e "  Database:  ${YELLOW}eduskript_dev${NC}"
echo ""
echo -e "${BLUE}Next.js:${NC}"
echo -e "  Port:      ${YELLOW}$NEXTJS_PORT${NC}"
echo -e "  URL:       ${YELLOW}http://localhost:$NEXTJS_PORT${NC}"
echo ""
echo -e "${BLUE}Admin Credentials:${NC}"
echo -e "  Email:     ${YELLOW}eduadmin@eduskript.org${NC}"
echo -e "  Password:  ${YELLOW}letseducate${NC}"
echo ""
echo -e "${BLUE}Next Steps:${NC}"
echo -e "  1. Start dev server:  ${GREEN}pnpm dev${NC}"
echo -e "  2. Open browser:      ${GREEN}http://localhost:$NEXTJS_PORT${NC}"
echo -e "  3. Sign in with admin credentials above"
echo ""
echo -e "${BLUE}Managing PostgreSQL:${NC}"
echo -e "  View logs:    ${GREEN}docker logs $POSTGRES_CONTAINER_NAME${NC}"
echo -e "  Stop:         ${GREEN}docker stop $POSTGRES_CONTAINER_NAME${NC}"
echo -e "  Start:        ${GREEN}docker start $POSTGRES_CONTAINER_NAME${NC}"
echo -e "  Remove:       ${GREEN}docker compose -f docker-compose.local.yml down -v${NC}"
echo ""
echo -e "${YELLOW}Note:${NC} This configuration is worktree-specific via .env.local"
echo -e "      You can run multiple worktrees simultaneously without port conflicts!"
echo ""
